# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: toxicity_classifier.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'toxicity_classifier.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19toxicity_classifier.proto\x12\x13toxicity_classifier\"!\n\x0eMessageRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"/\n\x0fMessageResponse\x12\x1c\n\x14toxicity_probability\x18\x01 \x01(\x02\x32t\n\x12ToxicityClassifier\x12^\n\x0f\x43lassifyMessage\x12#.toxicity_classifier.MessageRequest\x1a$.toxicity_classifier.MessageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'toxicity_classifier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=50
  _globals['_MESSAGEREQUEST']._serialized_end=83
  _globals['_MESSAGERESPONSE']._serialized_start=85
  _globals['_MESSAGERESPONSE']._serialized_end=132
  _globals['_TOXICITYCLASSIFIER']._serialized_start=134
  _globals['_TOXICITYCLASSIFIER']._serialized_end=250
# @@protoc_insertion_point(module_scope)
