# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import toxicity_classifier_pb2 as toxicity__classifier__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in toxicity_classifier_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ToxicityClassifierStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClassifyMessage = channel.unary_unary(
                '/toxicity_classifier.ToxicityClassifier/ClassifyMessage',
                request_serializer=toxicity__classifier__pb2.MessageRequest.SerializeToString,
                response_deserializer=toxicity__classifier__pb2.MessageResponse.FromString,
                _registered_method=True)


class ToxicityClassifierServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClassifyMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToxicityClassifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClassifyMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyMessage,
                    request_deserializer=toxicity__classifier__pb2.MessageRequest.FromString,
                    response_serializer=toxicity__classifier__pb2.MessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'toxicity_classifier.ToxicityClassifier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('toxicity_classifier.ToxicityClassifier', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ToxicityClassifier(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClassifyMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/toxicity_classifier.ToxicityClassifier/ClassifyMessage',
            toxicity__classifier__pb2.MessageRequest.SerializeToString,
            toxicity__classifier__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
