// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: toxicity_classifier.proto

#include "toxicity_classifier.pb.h"
#include "toxicity_classifier.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace toxicity_classifier {

static const char* ToxicityClassifier_method_names[] = {
  "/toxicity_classifier.ToxicityClassifier/ClassifyMessage",
};

std::unique_ptr< ToxicityClassifier::Stub> ToxicityClassifier::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ToxicityClassifier::Stub> stub(new ToxicityClassifier::Stub(channel, options));
  return stub;
}

ToxicityClassifier::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ClassifyMessage_(ToxicityClassifier_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ToxicityClassifier::Stub::ClassifyMessage(::grpc::ClientContext* context, const ::toxicity_classifier::MessageRequest& request, ::toxicity_classifier::MessageResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::toxicity_classifier::MessageRequest, ::toxicity_classifier::MessageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ClassifyMessage_, context, request, response);
}

void ToxicityClassifier::Stub::async::ClassifyMessage(::grpc::ClientContext* context, const ::toxicity_classifier::MessageRequest* request, ::toxicity_classifier::MessageResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::toxicity_classifier::MessageRequest, ::toxicity_classifier::MessageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ClassifyMessage_, context, request, response, std::move(f));
}

void ToxicityClassifier::Stub::async::ClassifyMessage(::grpc::ClientContext* context, const ::toxicity_classifier::MessageRequest* request, ::toxicity_classifier::MessageResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ClassifyMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::toxicity_classifier::MessageResponse>* ToxicityClassifier::Stub::PrepareAsyncClassifyMessageRaw(::grpc::ClientContext* context, const ::toxicity_classifier::MessageRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::toxicity_classifier::MessageResponse, ::toxicity_classifier::MessageRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ClassifyMessage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::toxicity_classifier::MessageResponse>* ToxicityClassifier::Stub::AsyncClassifyMessageRaw(::grpc::ClientContext* context, const ::toxicity_classifier::MessageRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncClassifyMessageRaw(context, request, cq);
  result->StartCall();
  return result;
}

ToxicityClassifier::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ToxicityClassifier_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ToxicityClassifier::Service, ::toxicity_classifier::MessageRequest, ::toxicity_classifier::MessageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ToxicityClassifier::Service* service,
             ::grpc::ServerContext* ctx,
             const ::toxicity_classifier::MessageRequest* req,
             ::toxicity_classifier::MessageResponse* resp) {
               return service->ClassifyMessage(ctx, req, resp);
             }, this)));
}

ToxicityClassifier::Service::~Service() {
}

::grpc::Status ToxicityClassifier::Service::ClassifyMessage(::grpc::ServerContext* context, const ::toxicity_classifier::MessageRequest* request, ::toxicity_classifier::MessageResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace toxicity_classifier

