// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: toxicity_classifier.proto
#ifndef GRPC_toxicity_5fclassifier_2eproto__INCLUDED
#define GRPC_toxicity_5fclassifier_2eproto__INCLUDED

#include "toxicity_classifier.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace toxicity_classifier {

class ToxicityClassifier final {
 public:
  static constexpr char const* service_full_name() {
    return "toxicity_classifier.ToxicityClassifier";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ClassifyMessage(::grpc::ClientContext* context, const ::toxicity_classifier::MessageRequest& request, ::toxicity_classifier::MessageResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::toxicity_classifier::MessageResponse>> AsyncClassifyMessage(::grpc::ClientContext* context, const ::toxicity_classifier::MessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::toxicity_classifier::MessageResponse>>(AsyncClassifyMessageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::toxicity_classifier::MessageResponse>> PrepareAsyncClassifyMessage(::grpc::ClientContext* context, const ::toxicity_classifier::MessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::toxicity_classifier::MessageResponse>>(PrepareAsyncClassifyMessageRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ClassifyMessage(::grpc::ClientContext* context, const ::toxicity_classifier::MessageRequest* request, ::toxicity_classifier::MessageResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ClassifyMessage(::grpc::ClientContext* context, const ::toxicity_classifier::MessageRequest* request, ::toxicity_classifier::MessageResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::toxicity_classifier::MessageResponse>* AsyncClassifyMessageRaw(::grpc::ClientContext* context, const ::toxicity_classifier::MessageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::toxicity_classifier::MessageResponse>* PrepareAsyncClassifyMessageRaw(::grpc::ClientContext* context, const ::toxicity_classifier::MessageRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ClassifyMessage(::grpc::ClientContext* context, const ::toxicity_classifier::MessageRequest& request, ::toxicity_classifier::MessageResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::toxicity_classifier::MessageResponse>> AsyncClassifyMessage(::grpc::ClientContext* context, const ::toxicity_classifier::MessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::toxicity_classifier::MessageResponse>>(AsyncClassifyMessageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::toxicity_classifier::MessageResponse>> PrepareAsyncClassifyMessage(::grpc::ClientContext* context, const ::toxicity_classifier::MessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::toxicity_classifier::MessageResponse>>(PrepareAsyncClassifyMessageRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ClassifyMessage(::grpc::ClientContext* context, const ::toxicity_classifier::MessageRequest* request, ::toxicity_classifier::MessageResponse* response, std::function<void(::grpc::Status)>) override;
      void ClassifyMessage(::grpc::ClientContext* context, const ::toxicity_classifier::MessageRequest* request, ::toxicity_classifier::MessageResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::toxicity_classifier::MessageResponse>* AsyncClassifyMessageRaw(::grpc::ClientContext* context, const ::toxicity_classifier::MessageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::toxicity_classifier::MessageResponse>* PrepareAsyncClassifyMessageRaw(::grpc::ClientContext* context, const ::toxicity_classifier::MessageRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ClassifyMessage_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ClassifyMessage(::grpc::ServerContext* context, const ::toxicity_classifier::MessageRequest* request, ::toxicity_classifier::MessageResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ClassifyMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ClassifyMessage() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ClassifyMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClassifyMessage(::grpc::ServerContext* /*context*/, const ::toxicity_classifier::MessageRequest* /*request*/, ::toxicity_classifier::MessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestClassifyMessage(::grpc::ServerContext* context, ::toxicity_classifier::MessageRequest* request, ::grpc::ServerAsyncResponseWriter< ::toxicity_classifier::MessageResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ClassifyMessage<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ClassifyMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ClassifyMessage() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::toxicity_classifier::MessageRequest, ::toxicity_classifier::MessageResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::toxicity_classifier::MessageRequest* request, ::toxicity_classifier::MessageResponse* response) { return this->ClassifyMessage(context, request, response); }));}
    void SetMessageAllocatorFor_ClassifyMessage(
        ::grpc::MessageAllocator< ::toxicity_classifier::MessageRequest, ::toxicity_classifier::MessageResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::toxicity_classifier::MessageRequest, ::toxicity_classifier::MessageResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ClassifyMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClassifyMessage(::grpc::ServerContext* /*context*/, const ::toxicity_classifier::MessageRequest* /*request*/, ::toxicity_classifier::MessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ClassifyMessage(
      ::grpc::CallbackServerContext* /*context*/, const ::toxicity_classifier::MessageRequest* /*request*/, ::toxicity_classifier::MessageResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ClassifyMessage<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ClassifyMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ClassifyMessage() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ClassifyMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClassifyMessage(::grpc::ServerContext* /*context*/, const ::toxicity_classifier::MessageRequest* /*request*/, ::toxicity_classifier::MessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ClassifyMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ClassifyMessage() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ClassifyMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClassifyMessage(::grpc::ServerContext* /*context*/, const ::toxicity_classifier::MessageRequest* /*request*/, ::toxicity_classifier::MessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestClassifyMessage(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ClassifyMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ClassifyMessage() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ClassifyMessage(context, request, response); }));
    }
    ~WithRawCallbackMethod_ClassifyMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClassifyMessage(::grpc::ServerContext* /*context*/, const ::toxicity_classifier::MessageRequest* /*request*/, ::toxicity_classifier::MessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ClassifyMessage(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ClassifyMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ClassifyMessage() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::toxicity_classifier::MessageRequest, ::toxicity_classifier::MessageResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::toxicity_classifier::MessageRequest, ::toxicity_classifier::MessageResponse>* streamer) {
                       return this->StreamedClassifyMessage(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ClassifyMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ClassifyMessage(::grpc::ServerContext* /*context*/, const ::toxicity_classifier::MessageRequest* /*request*/, ::toxicity_classifier::MessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedClassifyMessage(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::toxicity_classifier::MessageRequest,::toxicity_classifier::MessageResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ClassifyMessage<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ClassifyMessage<Service > StreamedService;
};

}  // namespace toxicity_classifier


#endif  // GRPC_toxicity_5fclassifier_2eproto__INCLUDED
