version: '3.8'

services:
  telemetry_server:
    image: telemetry-system
    volumes:
      - ./bin-output:/workspace/bin:ro
      - ./server/limits.json:/app/config/limits.json:ro 
    command: /workspace/bin/telemetry_server 12345 /app/config/limits.json
    networks:
      - telemetry_net

  telemetry_client:
    image: telemetry-system
    volumes:
      - ./bin-output:/workspace/bin:ro
    networks:
      - telemetry_net
    # Будет запущен тестовым раннером
    command: ["sleep", "infinity"] 

  test_runner:
    build: .
    volumes:
      - ./bin-output:/workspace/bin:ro
      - ./test_data:/test_data
    depends_on:
      - telemetry_server
      - telemetry_client
    networks:
      - telemetry_net
    command: /workspace/bin/functional_tests

networks:
  telemetry_net:
    driver: bridge

volumes:
  bin-output: